Select * From gold.dim_customers
Select * From gold.dim_products
Select * From gold.fact_sales

-- Retrieve a list of all tables in the database
SELECT 
    TABLE_CATALOG, 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES;

-- Retrieve all columns In dataset
Select 
    TABLE_CATALOG, 
    TABLE_SCHEMA, 
    TABLE_NAME, 
    COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS

-- Retrieve a list of unique countries from which customers originate
Select 
    distinct(country) as UNIQE_COUNTRY
FROM gold.dim_customers

-- Retrieve a list of unique categories, subcategories, and products
Select DISTINCT 
    category,
    subcategory,
    product_name
From gold.dim_products
ORDER BY 1,2,3 

-- Determine the first and last order date and the total duration in months
--How Many Years&month of sales are avlibale
Select 
    Max(order_date) as first_order,
    MIN(order_date) as last_order,
    DATEDIFF(YEAR,MIN(order_date),Max(order_date)) as [Order Range Years],
    DATEDIFF(MONTH,MIN(order_date),Max(order_date)) as [Order Range Months]
From gold.fact_sales

-- Find the youngest and oldest customer based on birthdate
Select 
    MAX(birthdate),
    DATEDIFF(YEAR,Min(birthdate),GETDATE())  as oldest , 
    MIN(birthdate),
    DATEDIFF(YEAR,Max(birthdate),GETDATE())  as youngest
from gold.dim_customers

-- Find the Total Sales
Select Sum(sales_amount) as total_sales FROM gold.fact_sales
-- Find how many items are sold
Select Sum(quantity) as quantity_sold FROM gold.fact_sales
-- Find the average selling price
Select avg(price) as avg_price FROM gold.fact_sales
-- Find the total number of customers & that has placed an order
Select COUNT(customer_key) as total_customers FROM gold.dim_customers
Select COUNT(distinct customer_key) as Uniqe_customers FROM gold.dim_customers
-- Find the Total number of Orders
Select COUNT(order_number) as total_customers FROM gold.fact_sales
Select COUNT(distinct order_number) as Uniqe_customers FROM gold.fact_sales
-- Find the total number of products
Select COUNT(product_key) as total_customers FROM gold.dim_products

-- Generate a Report that shows all key metrics of the business
Select 'total_sales' as measure_name,Sum(sales_amount) as measure_value FROM gold.fact_sales
UNION ALL
Select 'avg_price' as measure_name,avg(price) as measure_value FROM gold.fact_sales
UNION ALL
Select 'total_customers' as measure_name,COUNT(customer_key) as measure_value FROM gold.dim_customers
UNION ALL
Select 'Uniqe_customers' as measure_name,COUNT(distinct customer_key) as measure_value FROM gold.dim_customers
UNION ALL
Select 'total_orders' as measure_name,COUNT(order_number) as measure_value FROM gold.fact_sales
UNION ALL
Select 'Uniqe_order' as measure_name,COUNT(distinct order_number) as measure_value FROM gold.fact_sales
UNION ALL
Select 'total_products' as measure_name,COUNT(product_key) as measure_value FROM gold.dim_products

-- Find total customers by countries
Select 
    country,
    count(customer_key) as [total customer by counrty]
FROM gold.dim_customers
GROUP BY country
ORDER BY  count(customer_key) DESC
-- Find total customers by gender
Select 
    gender,
    count(customer_key) as [total customer by gender]
FROM gold.dim_customers
GROUP BY gender
ORDER BY  count(customer_key) DESC
-- Find total products by category
Select 
    category,
    count(product_key) as [total product by category]
FROM gold.dim_products
GROUP BY category
ORDER BY  count(product_key) DESC
-- What is the average costs in each category?
Select 
    category,
    AVG(cost) as [avg cost for each category]
FROM gold.dim_products
GROUP BY category
ORDER BY  AVG(cost) DESC
-- What is the total revenue generated for each category?
Select 
    d.category,
    SUM(p.sales_amount) as total_sales
FROM  gold.fact_sales p left JOIN gold.dim_products d 
ON    p.product_key = d.product_key
GROUP BY d.category
-- What is the total revenue generated by each customer?
Select 
    c.customer_id,
    CONCAT(c.first_name ,' ',c.last_name) as full_name,
    sum(sales_amount) as total_sales
FROM gold.dim_customers c left join gold.fact_sales f
ON c.customer_id = f.customer_key
GROUP BY c.customer_id,CONCAT(c.first_name ,' ',c.last_name)
ORDER BY sum(sales_amount) DESC


-- What is the distribution of sold items across countries?
Select 
    c.country,
    SUM(f.quantity) as total_quantity
FROM gold.dim_customers c left join gold.fact_sales f
ON c.customer_key = f.customer_key 
GROUP BY c.country
ORDER BY SUM(f.quantity) DESC

-- Which 5 products Generating the Highest Revenue?
Select *
from(
Select 
    p.subcategory,
    SUM(f.sales_amount) as total_sales,
    ROW_NUMBER() OVER(ORDER BY SUM(f.sales_amount) DESC) as ROW_NUMBER
FROM gold.dim_products p left join gold.fact_sales f 
ON p.product_key = f.product_key
GROUP BY p.subcategory) as T
where ROW_NUMBER <=5

-- Which 5 products Generating the LOWEST Revenue?
Select TOP 5
    p.subcategory,
    SUM(f.sales_amount) as total_sales
FROM gold.dim_products p left join gold.fact_sales f 
ON p.product_key = f.product_key
GROUP BY p.subcategory
ORDER BY SUM(f.sales_amount) ASC

-- Find the top 10 customers who have generated the highest revenue
Select TOP 5
    c.customer_id,
    CONCAT(c.first_name ,' ',c.last_name) as full_name,
    sum(sales_amount) as total_sales
FROM gold.dim_customers c left join gold.fact_sales f
ON c.customer_id = f.customer_key
GROUP BY c.customer_id,CONCAT(c.first_name ,' ',c.last_name)
ORDER BY sum(sales_amount) DESC

-- The 3 customers with the fewest orders placed
Select TOP 5
    c.customer_id,
    CONCAT(c.first_name ,' ',c.last_name) as full_name,
    sum(sales_amount) as total_sales
FROM gold.dim_customers c left join gold.fact_sales f
ON c.customer_id = f.customer_key
GROUP BY c.customer_id,CONCAT(c.first_name ,' ',c.last_name)
ORDER BY sum(sales_amount) 


------------------------------------------------------------------------------------------------------------------------
--ADVANCED QUERY

--Change Over Time Analysis


--SALES PERFORMANCE TREND: Compare current vs previous order_date sales and calculate difference
Select 
    order_date,
    COALESCE(SUM(sales_amount), 0) as TOTAL_SALES_current,
    --LAG(order_date) OVER(ORDER BY order_date)as previous_order_date,
    LAG(COALESCE(SUM(sales_amount), 0)) OVER(ORDER BY order_date)as total_sales_previous,
    COALESCE(SUM(sales_amount), 0) - LAG(COALESCE(SUM(sales_amount), 0)) OVER(ORDER BY order_date) AS DIFFENETSALES
FROM gold.fact_sales
GROUP BY order_date
HAVING order_date IS NOT NULL 
ORDER BY order_date
------ANALYSIS SALES PERFORMANCE OVER TIME
SELECT
    DATETRUNC(MONTH,order_date) AS [Start Month Of year],
    SUM(sales_amount) as total_sales,
    sum(quantity) as total_quantity,
    COUNT(DISTINCT customer_key) as customers
From gold.fact_sales
GROUP BY  DATETRUNC(MONTH,order_date),FORMAT(order_date,'yyyy-mmm')
HAVING DATETRUNC(MONTH,order_date)  IS NOT NULL
ORDER BY DATETRUNC(MONTH,order_date) 

SELECT
    --DATETRUNC(MONTH,order_date),
    FORMAT(order_date, 'yyyy-MMM' ) AS ORDERDATE,
    SUM(sales_amount) as total_sales,
    sum(quantity) as total_quantity,
    COUNT(DISTINCT customer_key) as customers
From gold.fact_sales
GROUP BY FORMAT(order_date,'yyyy-MMM')
HAVING FORMAT(order_date,'yyyy-MMM')  IS NOT NULL
ORDER BY FORMAT(order_date,'yyyy-MMM') 

-- Calculate the total sales per month 
Select
    FORMAT(order_date,'yyyy-MMM') as month_year,
    SUM(sales_amount) as TOTAL_SALES 
from gold.fact_sales
--WHERE FORMAT(order_date,'yyyy-MMM') IS NOT NULL
group by FORMAT(order_date,'yyyy-MMM')
HAVING FORMAT(order_date,'yyyy-MMM') IS NOT NULL
order by FORMAT(order_date, 'yyyy-MMM' )  asc
-- and the running total of sales over time
Select 
month_year,total_sales,
SUM(total_sales) over(ORDER BY month_year ASC) AS running_total_sales,
AVG(avg_price) over(ORDER BY month_year ASC) AS running_total_sales
from
(
Select
    DATETRUNC(MONTH,order_date) as month_year,
    SUM(sales_amount) as  total_sales,
    AVG(price) as avg_price
from gold.fact_sales
WHERE DATETRUNC(MONTH,order_date) IS NOT NULL
group by DATETRUNC(MONTH,order_date)
)t



--*/Analyze the yearly performance of products by comparing their sales 
--to both the average sales performance of the product and the previous year's sales */
WITH YEARLY_PRODUCT_SALES AS
(
Select 
    FORMAT(order_date,'yyyy') AS order_Year,
    p.product_name as product_name,
    SUM(sales_amount) AS Current_sales
FROM  gold.fact_sales f LEFT JOIN gold.dim_products  p
ON f.product_key = p.product_key
WHERE FORMAT(order_date,'yyyy') IS NOT NULL
GROUP BY 
FORMAT(order_date,'yyyy'),
p.product_name
)
Select 
order_Year,
product_name,
Current_sales,
LAG(Current_sales) OVER(PARTITION BY product_name ORDER BY order_Year) AS Prev_sales,
Current_sales - LAG(Current_sales) OVER(PARTITION BY product_name ORDER BY order_Year) AS DIFF_SALES ,
CASE WHEN Current_sales - LAG(Current_sales) OVER(PARTITION BY product_name ORDER BY order_Year) > 0 THEN 'Increase'
    WHEN  Current_sales - LAG(Current_sales) OVER(PARTITION BY product_name ORDER BY order_Year) < 0 THEN 'Decarese'
    ELSE 'no cahnge'
    END 'py change',
AVG(Current_sales) OVER(PARTITION BY product_name)  AS AVG_CURRENT_SALES,
Current_sales - AVG(Current_sales) OVER(PARTITION BY product_name) AS DIFF_AVG,
CASE WHEN Current_sales - AVG(Current_sales) OVER(PARTITION BY product_name) > 0THEN 'Above AVG'
     WHEN Current_sales - AVG(Current_sales) OVER(PARTITION BY product_name) < 0THEN 'below AVG'
     ELSE 'AVG'
     END AVG_CHANGE
FROM YEARLY_PRODUCT_SALES
ORDER BY product_name , order_Year 

-- Which categories contribute the most to overall sales?
WITH Category_Sales AS (
Select 
category,
sum(sales_amount) AS TOTAL_SALES
FROM gold.fact_sales f left join gold.dim_products p
ON f.product_key = p.product_key
GROUP BY category ) 
SELECT 
category,TOTAL_SALES,
SUM(TOTAL_SALES) OVER() AS Overall,
CONCAT(
    ROUND(
        (CAST(TOTAL_SALES AS FLOAT) / SUM(TOTAL_SALES) OVER()) * 100, 
        2
    ), '%'
) AS PREC_SALES
FROM Category_Sales

/*Segment products into cost ranges and 
count how many products fall into each segment*/

WITH cost_range AS(
Select 
product_key,
product_name,
cost,
CASE WHEN cost < 100 THEN 'Below 100'
     WHEN cost BETWEEN 100 AND 500 THEN '100-500'
     WHEN cost BETWEEN 500 AND 1000 THEN '500-1000'
     ELSE 'Above 1000'
     END 'COST_RANGE'
FROM gold.dim_products
)
SELECT 
COST_RANGE,
COUNT(COST_RANGE) AS TOTAL_PRODUCTS
FROM cost_range
GROUP BY cost_range
ORDER BY TOTAL_PRODUCTS DESC

/*Group customers into three segments based on their spending behavior:
	- VIP: Customers with at least 12 months of history and spending more than €5,000.
	- Regular: Customers with at least 12 months of history but spending €5,000 or less.
	- New: Customers with a lifespan less than 12 months.
And find the total number of customers by each group
*/
WITH customer_group AS(
Select 
c.customer_key AS customer_key,
sum(f.sales_amount) as total_spending,
MIN(order_date) as first_date,
MAX(order_date) as last_date,
DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan
FROM gold.dim_customers c LEFT JOIN gold.fact_sales f
ON c.customer_key = f.customer_key
WHERE order_date IS NOT NULL
GROUP BY 
c.customer_key
)
Select
customer_segment,
count(customer_key) as total_customers
from
(
Select
   customer_key,
   lifespan,
   total_spending,
        CASE 
            WHEN lifespan >= 12 AND total_spending > 5000 THEN 'VIP'
            WHEN lifespan >= 12 AND total_spending <= 5000 THEN 'Regular'
            ELSE 'New'
        END AS customer_segment
FROM customer_group) as segmented_customers
GROUP BY customer_segment

/*
===============================================================================
Customer Report
===============================================================================
Purpose:
    - This report consolidates key customer metrics and behaviors

Highlights:
    1. Gathers essential fields such as names, ages, and transaction details.
	2. Segments customers into categories (VIP, Regular, New) and age groups.
    3. Aggregates customer-level metrics:
	   - total orders
	   - total sales
	   - total quantity purchased
	   - total products
	   - lifespan (in months)
    4. Calculates valuable KPIs:
	    - recency (months since last order)
		- average order value
		- average monthly spend
===============================================================================
*/

IF OBJECT_ID('gold.report_customers', 'V') IS NOT NULL
    DROP VIEW gold.report_customers;
GO

CREATE VIEW gold.report_customers AS
WITH base_query AS(
/*---------------------------------------------------------------------------
1) Base Query: Retrieves core columns from tables
---------------------------------------------------------------------------*/
SELECT
f.order_number,
f.product_key,
f.order_date,
f.sales_amount,
f.quantity,
c.customer_key,
c.customer_number,
CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
DATEDIFF(year, c.birthdate, GETDATE()) age
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
WHERE order_date IS NOT NULL)

, customer_aggregation AS (
/*---------------------------------------------------------------------------
2) Customer Aggregations: Summarizes key metrics at the customer level
---------------------------------------------------------------------------*/
SELECT 
	customer_key,
	customer_number,
	customer_name,
	age,
	COUNT(DISTINCT order_number) AS total_orders,
	SUM(sales_amount) AS total_sales,
	SUM(quantity) AS total_quantity,
	COUNT(DISTINCT product_key) AS total_products,
	MAX(order_date) AS last_order_date,
	DATEDIFF(month, MIN(order_date), MAX(order_date)) AS lifespan
FROM base_query
GROUP BY 
	customer_key,
	customer_number,
	customer_name,
	age
)
SELECT
customer_key,
customer_number,
customer_name,
age,
CASE 
	 WHEN age < 20 THEN 'Under 20'
	 WHEN age between 20 and 29 THEN '20-29'
	 WHEN age between 30 and 39 THEN '30-39'
	 WHEN age between 40 and 49 THEN '40-49'
	 ELSE '50 and above'
END AS age_group,
CASE 
    WHEN lifespan >= 12 AND total_sales > 5000 THEN 'VIP'
    WHEN lifespan >= 12 AND total_sales <= 5000 THEN 'Regular'
    ELSE 'New'
END AS customer_segment,
last_order_date,
DATEDIFF(month, last_order_date, GETDATE()) AS recency,
total_orders,
total_sales,
total_quantity,
total_products
lifespan,
-- Compuate average order value (AVO)
CASE WHEN total_sales = 0 THEN 0
	 ELSE total_sales / total_orders
END AS avg_order_value,
-- Compuate average monthly spend
CASE WHEN lifespan = 0 THEN total_sales
     ELSE total_sales / lifespan
END AS avg_monthly_spend
FROM customer_aggregation


-------------------------------------------------------------------
IF OBJECT_ID('gold.report_products', 'V') IS NOT NULL
    DROP VIEW gold.report_products;
GO

CREATE VIEW gold.report_products AS

WITH base_query AS (
/*---------------------------------------------------------------------------
1) Base Query: Retrieves core columns from fact_sales and dim_products
---------------------------------------------------------------------------*/
    SELECT
	    f.order_number,
        f.order_date,
		f.customer_key,
        f.sales_amount,
        f.quantity,
        p.product_key,
        p.product_name,
        p.category,
        p.subcategory,
        p.cost
    FROM gold.fact_sales f
    LEFT JOIN gold.dim_products p
        ON f.product_key = p.product_key
    WHERE order_date IS NOT NULL  -- only consider valid sales dates
),

product_aggregations AS (
/*---------------------------------------------------------------------------
2) Product Aggregations: Summarizes key metrics at the product level
---------------------------------------------------------------------------*/
SELECT
    product_key,
    product_name,
    category,
    subcategory,
    cost,
    DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS lifespan,
    MAX(order_date) AS last_sale_date,
    COUNT(DISTINCT order_number) AS total_orders,
	COUNT(DISTINCT customer_key) AS total_customers,
    SUM(sales_amount) AS total_sales,
    SUM(quantity) AS total_quantity,
	ROUND(AVG(CAST(sales_amount AS FLOAT) / NULLIF(quantity, 0)),1) AS avg_selling_price
FROM base_query

GROUP BY
    product_key,
    product_name,
    category,
    subcategory,
    cost
)

/*---------------------------------------------------------------------------
  3) Final Query: Combines all product results into one output
---------------------------------------------------------------------------*/
SELECT 
	product_key,
	product_name,
	category,
	subcategory,
	cost,
	last_sale_date,
	DATEDIFF(MONTH, last_sale_date, GETDATE()) AS recency_in_months,
	CASE
		WHEN total_sales > 50000 THEN 'High-Performer'
		WHEN total_sales >= 10000 THEN 'Mid-Range'
		ELSE 'Low-Performer'
	END AS product_segment,
	lifespan,
	total_orders,
	total_sales,
	total_quantity,
	total_customers,
	avg_selling_price,
	-- Average Order Revenue (AOR)
	CASE 
		WHEN total_orders = 0 THEN 0
		ELSE total_sales / total_orders
	END AS avg_order_revenue,

	-- Average Monthly Revenue
	CASE
		WHEN lifespan = 0 THEN total_sales
		ELSE total_sales / lifespan
	END AS avg_monthly_revenue

FROM product_aggregations 

SELECT * FROM gold.report_products;
SELECT * FROM gold.report_customers;